%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------

# rate of systemmatic samplling for events (均匀采样率)
sampling_rate: 3
# rate of systemmatic samplling for globally aligned events
map_sampling_rate: 3
# event image theshold T_rho
event_image_threshold: 5
# on/off (1/0) the proposed method (是否启用angular position compensator)
rotation_estimation: 1


# view contrast maximization process after view_idex
optimization_view_index: 1e3
# view angle difference range to utilize globally aligned events (unit: radians) 
mapping_interval: 0.628
# scale of view for globally aligned events
map_scale: 2


#--------------------------------------------------------------------------------------------
# Optimizer Parameters
#--------------------------------------------------------------------------------------------

# maximum iteration
Optimizer.max_iter: 65 
# poster-65, boxes-80, dynamic-55, shapes-65
# building-75, staircase-90, blocks-55, miscellany-45, bicycles-45, cabinets-45

# step size | optimization rate
Optimizer.mu_angular_velocity: 0.05
# smoothing factor | the degree of weigthing decrease in geometric moving average  
Optimizer.rho_angular_velocity: 0.995

# step size | optimization rate
Optimizer.mu_angular_acc1: 0.01 #0.9
# smoothing factor | the degree of weigthing decrease in geometric moving average  
Optimizer.rho_angular_acc1: 0.995

# step size | optimization rate
Optimizer.mu_angular_acc2: 0.01 #0.9
# smoothing factor | the degree of weigthing decrease in geometric moving average  
Optimizer.rho_angular_acc2: 0.995

# step size | optimization rate
Optimizer.mu_angular_position: 0.0025
# smoothing factor | the degree of weigthing decrease in geometric moving average  
Optimizer.rho_angular_position: 0.05

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
# size of real targets

##############
# Kim datasets
##############
# width: 240
# height: 180

# # focus
# Camera.fx: 230.2097
# Camera.fy: 231.1228
# # center
# Camera.cx: 121.6862
# Camera.cy: 86.8208
# # radial distortion
# Camera.rd1: -0.4136
# Camera.rd2: 0.2042

##############
# rpg_uzh datasets
##############
# width: 240
# height: 180

# # focus
# Camera.fx: 199.0924
# Camera.fy: 198.8288
# # center
# Camera.cx: 132.1921
# Camera.cy: 110.7127
# # radial distortion
# Camera.rd1: -0.3684
# Camera.rd2: 0.1509

##############
# Our datasets
##############
width: 346
height: 260

# focus
Camera.fx: 442.3540
Camera.fy: 442.6880
# center
Camera.cx: 184.4289
Camera.cy: 138.2098
# radial distortion
Camera.rd1: -0.3346
Camera.rd2: 0.1299

visualize.denom: 3
